name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          check-latest: true
      
      - name: npm install 🏗
        run: npm install
      
      - name: npm build 🏭
        run: npm run build

      - name: npm deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true